name: Build and push multi-arch ubuntu-systemd Docker image

on:
  push:
    paths:
      - 'ubuntu-systemd/Dockerfile'
  pull_request:
    paths:
      - 'ubuntu-systemd/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create init
        run: |
          if [ ${{ matrix.architecture}} == arm64 ]; then
            apt install -y g++-aarch64-linux-gnu
            aarch64-linux-gnu-g++ ubuntu-systemd/init.cpp -o ubuntu-systemd/init
          else
            apt install -y g++
            g++ ubuntu-systemd/init.cpp -o ubuntu-systemd/init
          fi
          file ubuntu-systemd/init

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ubuntu-systemd/Dockerfile
          push: true
          tags: kaylor/ubuntu-systemd:latest
          platforms: linux/${{ matrix.architecture}}

      - name: Logout of DockerHub
        run: docker logout